//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public string Food { get; set; }
        public Nullable<int> QuantityofFood { get; set; }
        public Nullable<int> PriceofFood { get; set; }
        public string Drink { get; set; }
        public Nullable<int> QuantityofDrink { get; set; }
        public Nullable<int> PriceofDrink { get; set; }
        public Nullable<int> Total { get; set; }
        public string ID_Table { get; set; }
    
        public virtual Table Table { get; set; }
    }
}
